// Mapping from cloc language names to Devicon icon slugs
// Full list: https://devicon.dev/

const LANGUAGE_ICONS: Record<string, string> = {
  'Python': 'python',
  'JavaScript': 'javascript',
  'TypeScript': 'typescript',
  'Java': 'java',
  'C': 'c',
  'C++': 'cplusplus',
  'C#': 'csharp',
  'Go': 'go',
  'Rust': 'rust',
  'Ruby': 'ruby',
  'PHP': 'php',
  'Swift': 'swift',
  'Kotlin': 'kotlin',
  'Dart': 'dart',
  'Scala': 'scala',
  'R': 'r',
  'Perl': 'perl',
  'Lua': 'lua',
  'Haskell': 'haskell',
  'Elixir': 'elixir',
  'Erlang': 'erlang',
  'Clojure': 'clojure',
  'Julia': 'julia',
  'OCaml': 'ocaml',
  'HTML': 'html5',
  'CSS': 'css3',
  'Sass': 'sass',
  'SCSS': 'sass',
  'Less': 'less',
  'SQL': 'azuresqldatabase',
  'Shell': 'bash',
  'Bash': 'bash',
  'PowerShell': 'powershell',
  'Dockerfile': 'docker',
  'Terraform': 'terraform',
  'Objective-C': 'objectivec',
  'Objective-C++': 'objectivec',
  'Assembly': 'wasm',
  'Astro': 'astro',
  'Groovy': 'groovy',
  'Vue.js': 'vuejs',
  'Svelte': 'svelte',
};

export function getLanguageIconUrl(language: string): string | null {
  const slug = LANGUAGE_ICONS[language];
  if (!slug) return null;
  return `https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/${slug}/${slug}-original.svg`;
}

// GitHub-style language colors
const LANGUAGE_COLORS: Record<string, string> = {
  'Python': '#3572A5',
  'JavaScript': '#f1e05a',
  'TypeScript': '#3178c6',
  'Java': '#b07219',
  'C': '#555555',
  'C++': '#f34b7d',
  'C#': '#178600',
  'Go': '#00ADD8',
  'Rust': '#dea584',
  'Ruby': '#701516',
  'PHP': '#4F5D95',
  'Swift': '#F05138',
  'Kotlin': '#A97BFF',
  'Dart': '#00B4AB',
  'Scala': '#c22d40',
  'R': '#198CE7',
  'Perl': '#0298c3',
  'Lua': '#000080',
  'Haskell': '#5e5086',
  'Elixir': '#6e4a7e',
  'Erlang': '#B83998',
  'Clojure': '#db5855',
  'Julia': '#a270ba',
  'OCaml': '#3be133',
  'HTML': '#e34c26',
  'CSS': '#563d7c',
  'Sass': '#a53b70',
  'SCSS': '#c6538c',
  'Less': '#1d365d',
  'SQL': '#e38c00',
  'Shell': '#89e051',
  'Bash': '#89e051',
  'PowerShell': '#012456',
  'Dockerfile': '#384d54',
  'Terraform': '#5C4EE5',
  'Objective-C': '#438eff',
  'Vue.js': '#41b883',
  'Svelte': '#ff3e00',
  'XML': '#0060ac',
  'AsciiDoc': '#73a0c5',
  'Groovy': '#4298b8',
  'Assembly': '#6E4C13',
  'Astro': '#ff5d01',
};

export function getLanguageColor(language: string): string {
  return LANGUAGE_COLORS[language] || '#8b949e';
}
